name: Waka Readme

on:
  # This allows you to trigger the workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          TIME_RANGE: last_year
          SHOW_TOTAL: true
          LANG_COUNT: 20
          SHOW_TITLE: true
          COMMITTER_NAME: snnbyyds
          COMMITTER_EMAIL: snnbyyds@gmail.com
          AUTHOR_NAME: snnbyyds
          AUTHOR_EMAIL: snnbyyds@gmail.com
